-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analytics_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type character varying NOT NULL,
  user_id character varying NOT NULL,
  user_type character varying NOT NULL CHECK (user_type::text = ANY (ARRAY['trainer'::character varying, 'client'::character varying]::text[])),
  metadata jsonb DEFAULT '{}'::jsonb,
  device_info jsonb DEFAULT '{}'::jsonb,
  timestamp timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.art_director_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prompt_id uuid NOT NULL,
  series_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'analyzing'::text CHECK (status = ANY (ARRAY['analyzing'::text, 'awaiting_selection'::text, 'generating'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  intent_analysis jsonb,
  reference_images jsonb,
  selected_reference_id integer,
  adapted_recipe jsonb,
  iterations jsonb NOT NULL DEFAULT '[]'::jsonb,
  current_iteration integer NOT NULL DEFAULT 0,
  best_iteration integer,
  best_score numeric,
  final_image_url text,
  final_image_id uuid,
  error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT art_director_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT art_director_jobs_final_image_id_fkey FOREIGN KEY (final_image_id) REFERENCES public.images(id)
);
CREATE TABLE public.authors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  portrait_url text,
  bio_short text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT authors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.characters (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_image_id uuid,
  approved_fullbody_image_id uuid,
  approved_seed integer,
  approved_fullbody_seed integer,
  approved_prompt text,
  approved_fullbody_prompt text,
  portrait_prompt_locked text,
  archetype_tag text,
  vibe_line text,
  wants text,
  needs text,
  defining_quote text,
  watch_out_for text,
  bio_short text,
  card_image_prompt text,
  card_image_url text,
  card_image_id uuid,
  card_approved_at timestamp with time zone,
  author_id uuid NOT NULL,
  character_slug text CHECK (character_slug IS NULL OR character_slug ~ '^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$'::text),
  body_invalidated_at timestamp with time zone,
  CONSTRAINT characters_pkey PRIMARY KEY (id),
  CONSTRAINT characters_approved_image_id_fkey FOREIGN KEY (approved_image_id) REFERENCES public.images(id),
  CONSTRAINT characters_approved_fullbody_image_id_fkey FOREIGN KEY (approved_fullbody_image_id) REFERENCES public.images(id),
  CONSTRAINT characters_card_image_id_fkey FOREIGN KEY (card_image_id) REFERENCES public.images(id),
  CONSTRAINT characters_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.authors(id)
);
CREATE TABLE public.dashboard_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['trainer'::text, 'client'::text])),
  purpose text NOT NULL DEFAULT 'dashboard'::text,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  used boolean DEFAULT false,
  used_at timestamp with time zone,
  CONSTRAINT dashboard_tokens_pkey PRIMARY KEY (id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  event_type text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.generation_evaluations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  image_id uuid NOT NULL,
  prompt_id uuid NOT NULL,
  attempt_number integer NOT NULL,
  composition_type text NOT NULL CHECK (composition_type = ANY (ARRAY['solo'::text, '1boy_1girl'::text, '1girl_1girl'::text, '1boy_1boy'::text, 'group'::text])),
  content_mode text NOT NULL CHECK (content_mode = ANY (ARRAY['sfw'::text, 'nsfw'::text])),
  original_prose text NOT NULL,
  booru_tags text NOT NULL,
  generation_params jsonb NOT NULL DEFAULT '{}'::jsonb,
  person_count_expected integer NOT NULL,
  person_count_detected integer,
  setting_score smallint CHECK (setting_score >= 1 AND setting_score <= 5),
  clothing_score smallint CHECK (clothing_score >= 1 AND clothing_score <= 5),
  pose_score smallint CHECK (pose_score >= 1 AND pose_score <= 5),
  lighting_score smallint CHECK (lighting_score >= 1 AND lighting_score <= 5),
  composition_score smallint CHECK (composition_score >= 1 AND composition_score <= 5),
  character_distinction_score smallint CHECK (character_distinction_score >= 1 AND character_distinction_score <= 5),
  overall_score numeric,
  passed boolean NOT NULL DEFAULT false,
  failure_categories ARRAY NOT NULL DEFAULT '{}'::text[],
  corrections_applied jsonb,
  eval_model text NOT NULL DEFAULT 'claude-haiku-4-5-20251001'::text,
  raw_eval_response jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  intent_score numeric DEFAULT NULL::numeric,
  CONSTRAINT generation_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT generation_evaluations_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.images(id)
);
CREATE TABLE public.generation_jobs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  job_id text NOT NULL UNIQUE,
  image_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  cost numeric,
  error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  job_type text NOT NULL DEFAULT 'scene_image'::text CHECK (job_type = ANY (ARRAY['scene_image'::text, 'cover_variant'::text, 'character_portrait'::text, 'character_card'::text, 'author_note'::text])),
  variant_index integer CHECK (variant_index IS NULL OR variant_index >= 0 AND variant_index <= 3),
  series_id uuid,
  CONSTRAINT generation_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT generation_jobs_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.story_series(id),
  CONSTRAINT generation_jobs_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.images(id)
);
CREATE TABLE public.images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  character_id uuid,
  sfw_url text,
  nsfw_url text,
  prompt text NOT NULL,
  negative_prompt text NOT NULL DEFAULT ''::text,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  mode text NOT NULL DEFAULT 'sfw'::text CHECK (mode = ANY (ARRAY['sfw'::text, 'nsfw'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  stored_url text,
  critique text,
  requested_width integer,
  requested_height integer,
  actual_width integer,
  actual_height integer,
  dimension_fallback_reason text,
  CONSTRAINT images_pkey PRIMARY KEY (id),
  CONSTRAINT images_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.characters(id)
);
CREATE TABLE public.nsw_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  subscription_id uuid,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'ZAR'::text,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'succeeded'::text, 'failed'::text, 'refunded'::text])),
  payment_provider text CHECK (payment_provider = ANY (ARRAY['paystack'::text, 'yoco'::text, 'stripe'::text, 'payfast'::text])),
  provider_payment_id text UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT nsw_payments_pkey PRIMARY KEY (id),
  CONSTRAINT nsw_payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.nsw_users(id),
  CONSTRAINT nsw_payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.nsw_subscriptions(id)
);
CREATE TABLE public.nsw_purchases (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  series_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'ZAR'::text,
  payment_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT nsw_purchases_pkey PRIMARY KEY (id),
  CONSTRAINT nsw_purchases_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.nsw_users(id),
  CONSTRAINT nsw_purchases_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.story_series(id),
  CONSTRAINT nsw_purchases_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.nsw_payments(id)
);
CREATE TABLE public.nsw_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  plan text NOT NULL CHECK (plan = ANY (ARRAY['free'::text, 'basic'::text, 'premium'::text, 'enterprise'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'expired'::text, 'trial'::text])),
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  payfast_token text UNIQUE,
  cancel_at_period_end boolean DEFAULT false,
  is_founding_member boolean NOT NULL DEFAULT false,
  locked_rate_cents integer,
  rate_locked_until timestamp with time zone,
  CONSTRAINT nsw_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT nsw_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.nsw_users(id)
);
CREATE TABLE public.nsw_users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  auth_user_id uuid NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  display_name text,
  role text NOT NULL DEFAULT 'viewer'::text CHECK (role = ANY (ARRAY['admin'::text, 'editor'::text, 'viewer'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  phone text,
  has_whatsapp boolean NOT NULL DEFAULT false,
  has_email boolean NOT NULL DEFAULT false,
  both_channels_bonus boolean NOT NULL DEFAULT false,
  nurture_started_at timestamp with time zone,
  CONSTRAINT nsw_users_pkey PRIMARY KEY (id),
  CONSTRAINT nsw_users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.page_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  page_path text NOT NULL,
  page_title text,
  referrer text,
  referrer_domain text,
  country_code character varying,
  device_type character varying,
  browser character varying,
  os character varying,
  user_agent text,
  response_time_ms integer,
  session_id uuid,
  is_new_session boolean DEFAULT false,
  CONSTRAINT page_views_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payfast_itn_events (
  pf_payment_id text NOT NULL,
  m_payment_id text,
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  payment_status text,
  raw_payload jsonb NOT NULL,
  CONSTRAINT payfast_itn_events_pkey PRIMARY KEY (pf_payment_id)
);
CREATE TABLE public.pose_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  pose_description text NOT NULL,
  image_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  send_image_to_model boolean NOT NULL DEFAULT false,
  CONSTRAINT pose_templates_pkey PRIMARY KEY (id),
  CONSTRAINT pose_templates_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.images(id)
);
CREATE TABLE public.sessions (
  session_id uuid NOT NULL,
  first_seen timestamp with time zone DEFAULT now(),
  last_seen timestamp with time zone DEFAULT now(),
  page_count integer DEFAULT 1,
  country_code character varying,
  device_type character varying,
  browser character varying,
  os character varying,
  CONSTRAINT sessions_pkey PRIMARY KEY (session_id)
);
CREATE TABLE public.story_characters (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  series_id uuid NOT NULL,
  character_id uuid NOT NULL,
  role text DEFAULT 'supporting'::text CHECK (role = ANY (ARRAY['protagonist'::text, 'love_interest'::text, 'supporting'::text, 'antagonist'::text])),
  prose_description text,
  CONSTRAINT story_characters_pkey PRIMARY KEY (id),
  CONSTRAINT story_characters_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.characters(id),
  CONSTRAINT story_characters_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.story_series(id)
);
CREATE TABLE public.story_image_prompts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  post_id uuid NOT NULL,
  image_type text NOT NULL CHECK (image_type = ANY (ARRAY['facebook_sfw'::text, 'website_nsfw_paired'::text, 'website_only'::text])),
  pairs_with uuid,
  position integer NOT NULL DEFAULT 1,
  position_after_word integer,
  character_name text,
  character_id uuid,
  prompt text NOT NULL,
  image_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'generating'::text, 'generated'::text, 'approved'::text, 'failed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  secondary_character_name text,
  secondary_character_id uuid,
  debug_data jsonb,
  sfw_image_id uuid,
  previous_image_id uuid,
  character_block_override text,
  secondary_character_block_override text,
  suppress_character_block boolean NOT NULL DEFAULT false,
  clothing_override text,
  sfw_constraint_override text,
  visual_signature_override text,
  final_prompt text,
  final_prompt_drafted_at timestamp with time zone,
  pose_template_id uuid,
  is_chapter_hero boolean NOT NULL DEFAULT false,
  excluded_from_publish boolean NOT NULL DEFAULT false,
  primary_ref_type text NOT NULL DEFAULT 'body'::text CHECK (primary_ref_type = ANY (ARRAY['face'::text, 'body'::text])),
  secondary_ref_type text CHECK (secondary_ref_type IS NULL OR (secondary_ref_type = ANY (ARRAY['face'::text, 'body'::text]))),
  CONSTRAINT story_image_prompts_pkey PRIMARY KEY (id),
  CONSTRAINT story_image_prompts_pose_template_id_fkey FOREIGN KEY (pose_template_id) REFERENCES public.pose_templates(id),
  CONSTRAINT story_image_prompts_pairs_with_fkey FOREIGN KEY (pairs_with) REFERENCES public.story_image_prompts(id),
  CONSTRAINT story_image_prompts_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.story_posts(id),
  CONSTRAINT story_image_prompts_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.characters(id),
  CONSTRAINT story_image_prompts_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.images(id),
  CONSTRAINT story_image_prompts_secondary_character_id_fkey FOREIGN KEY (secondary_character_id) REFERENCES public.characters(id),
  CONSTRAINT story_image_prompts_sfw_image_id_fkey FOREIGN KEY (sfw_image_id) REFERENCES public.images(id),
  CONSTRAINT story_image_prompts_previous_image_id_fkey FOREIGN KEY (previous_image_id) REFERENCES public.images(id)
);
CREATE TABLE public.story_posts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  series_id uuid NOT NULL,
  part_number integer NOT NULL,
  title text NOT NULL,
  facebook_content text NOT NULL,
  facebook_teaser text,
  facebook_comment text,
  website_content text NOT NULL,
  hashtags ARRAY DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'images_pending'::text, 'images_approved'::text, 'ready'::text, 'scheduled'::text, 'published'::text])),
  facebook_post_id text,
  published_at timestamp with time zone,
  scheduled_for timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  buffer_post_id text,
  buffer_status text,
  buffer_error text,
  CONSTRAINT story_posts_pkey PRIMARY KEY (id),
  CONSTRAINT story_posts_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.story_series(id)
);
CREATE TABLE public.story_series (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  total_parts integer NOT NULL DEFAULT 1,
  hashtag text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'characters_pending'::text, 'images_pending'::text, 'review'::text, 'scheduled'::text, 'published'::text, 'archived'::text])),
  marketing jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  image_engine text NOT NULL DEFAULT 'pony_cyberreal'::text CHECK (image_engine = ANY (ARRAY['kontext'::text, 'nb2_uncanny'::text, 'flux_pulid'::text, 'pony_cyberreal'::text, 'juggernaut_ragnarok'::text])),
  image_model text NOT NULL DEFAULT 'flux2_dev'::text CHECK (image_model = ANY (ARRAY['flux2_dev'::text, 'hunyuan3'::text])),
  cover_prompt text,
  cover_base_url text,
  cover_variants jsonb,
  cover_selected_variant integer CHECK (cover_selected_variant IS NULL OR cover_selected_variant >= 0 AND cover_selected_variant <= 3),
  cover_sizes jsonb,
  cover_status text NOT NULL DEFAULT 'pending'::text CHECK (cover_status = ANY (ARRAY['pending'::text, 'generating'::text, 'variants_ready'::text, 'approved'::text, 'compositing'::text, 'complete'::text, 'failed'::text])),
  blurb_short_variants jsonb,
  blurb_short_selected integer CHECK (blurb_short_selected IS NULL OR blurb_short_selected >= 0 AND blurb_short_selected <= 2),
  blurb_long_variants jsonb,
  blurb_long_selected integer CHECK (blurb_long_selected IS NULL OR blurb_long_selected >= 0 AND blurb_long_selected <= 2),
  cover_error text,
  author_notes jsonb,
  cover_secondary_character_id uuid,
  published_at timestamp with time zone,
  access_tier text NOT NULL DEFAULT 'paid'::text CHECK (access_tier = ANY (ARRAY['free_authenticated'::text, 'paid'::text])),
  cover_post_buffer_id text,
  cover_post_status text,
  cover_post_error text,
  cover_post_scheduled_for timestamp with time zone,
  cover_post_published_at timestamp with time zone,
  cover_post_facebook_id text,
  cover_post_cta_line text,
  cover_primary_ref_type text NOT NULL DEFAULT 'body'::text CHECK (cover_primary_ref_type = ANY (ARRAY['face'::text, 'body'::text])),
  cover_secondary_ref_type text CHECK (cover_secondary_ref_type IS NULL OR (cover_secondary_ref_type = ANY (ARRAY['face'::text, 'body'::text]))),
  author_id uuid NOT NULL,
  author_note_image_prompt text,
  author_note_image_url text,
  author_note_publish_states jsonb NOT NULL DEFAULT '{}'::jsonb,
  author_note_image_id uuid,
  author_note_approved_at timestamp with time zone,
  author_note_buffer_post_id text,
  author_note_buffer_status text,
  author_note_buffer_error text,
  author_note_scheduled_for timestamp with time zone,
  CONSTRAINT story_series_pkey PRIMARY KEY (id),
  CONSTRAINT story_series_cover_secondary_character_id_fkey FOREIGN KEY (cover_secondary_character_id) REFERENCES public.characters(id),
  CONSTRAINT story_series_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.authors(id),
  CONSTRAINT story_series_author_note_image_id_fkey FOREIGN KEY (author_note_image_id) REFERENCES public.images(id)
);
CREATE TABLE public.subscribers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email USER-DEFINED NOT NULL UNIQUE CHECK (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'::citext),
  whatsapp_number text CHECK (whatsapp_number IS NULL OR whatsapp_number ~ '^\+[1-9]\d{7,14}$'::text),
  email_marketing_consent boolean NOT NULL DEFAULT false,
  whatsapp_marketing_consent boolean NOT NULL DEFAULT false,
  source_series_slug text,
  source_chapter_number integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  consent_recorded_at timestamp with time zone,
  unsubscribed_at timestamp with time zone,
  CONSTRAINT subscribers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.whatsapp_pins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone text NOT NULL,
  pin text NOT NULL,
  story_slug text NOT NULL,
  chapter integer NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  verified_at timestamp with time zone,
  attempts integer NOT NULL DEFAULT 0,
  locked_until timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  email USER-DEFINED,
  CONSTRAINT whatsapp_pins_pkey PRIMARY KEY (id)
);