/**
 * V4 Scene Image Generation: Multi-LoRA + Easel Face Swap via Replicate
 *
 * Two-step cloud pipeline — no RunPod, no ComfyUI, no PuLID:
 *
 * Step 1: lucataco/flux-dev-multi-lora (scene generation)
 *   Flux 1 Dev + Uncensored LoRA for NSFW, optional style LoRAs.
 *   Generates scene with natural poses — no character identity yet.
 *
 * Step 2: easel/advanced-face-swap (character identity)
 *   Takes the generated scene + approved character face portraits.
 *   Swaps in correct faces, preserving scene/lighting/skin tone.
 *   Supports 1 or 2 faces per pass for dual-character scenes.
 *
 * Synchronous: both Replicate calls return results directly (no job polling).
 */

import { supabase } from "@no-safe-word/story-engine";
import { runV4Pipeline } from "@no-safe-word/image-gen";
import type { V4PipelineResult } from "@no-safe-word/image-gen";

// Re-export fetchCharacterDataMap from V1 — shared across all pipelines
export { fetchCharacterDataMap } from "./generate-scene-image";

// ── Types ──

export interface ScenePromptInput {
  id: string;
  image_type: string;
  position: number;
  character_id: string | null;
  character_name: string | null;
  secondary_character_id: string | null;
  secondary_character_name: string | null;
  prompt: string;
}

export interface V4SceneResult {
  imageBuffer: Buffer;
  imageBase64: string;
  assembledPrompt: string;
  mode: "sfw" | "nsfw";
  seed: number;
  engine: "flux2_pro";
  hasFaceSwap: boolean;
  /** Pre-face-swap scene image for debugging */
  sceneImageBase64: string;
}

interface V4GenerateSceneParams {
  imgPrompt: ScenePromptInput;
  seriesId: string;
  seed: number;
}

// ── Helpers ──

/**
 * Fetch the approved face URL for a character.
 * Face swap only needs the face portrait — body is generated by the scene step.
 *
 * Sources (in priority order):
 * 1. story_characters.face_url (direct URL from character approval)
 * 2. story_characters.approved_image_id → images.stored_url (legacy lookup)
 */
async function fetchApprovedFaceUrl(
  seriesId: string,
  characterId: string,
  charName: string,
): Promise<string | null> {
  const { data: sc, error } = await (supabase as any)
    .from("story_characters")
    .select("face_url, approved_image_id")
    .eq("series_id", seriesId)
    .eq("character_id", characterId)
    .single() as {
      data: {
        face_url: string | null;
        approved_image_id: string | null;
      } | null;
      error: any;
    };

  if (error || !sc) {
    console.warn(`[V4] Character "${charName}" not found in series — no face for swap`);
    return null;
  }

  // Direct face URL (preferred)
  if (sc.face_url) {
    return sc.face_url;
  }

  // Legacy: approved_image_id → images table lookup
  if (sc.approved_image_id) {
    const { data: img } = await supabase
      .from("images")
      .select("stored_url, sfw_url")
      .eq("id", sc.approved_image_id)
      .single();

    const url = img?.stored_url || img?.sfw_url;
    if (url) return url;
  }

  console.warn(`[V4] Character "${charName}" has no face image — face swap will be skipped`);
  return null;
}

/**
 * Resolve character gender from the characters table description JSONB.
 * Falls back to "female" (default for this project's characters).
 */
async function getCharacterGender(characterId: string): Promise<"male" | "female"> {
  const { data } = await supabase
    .from("characters")
    .select("description")
    .eq("id", characterId)
    .single();

  const desc = data?.description as Record<string, string> | null;
  const gender = desc?.gender?.toLowerCase();
  return gender === "male" ? "male" : "female";
}

// ── Main Pipeline ──

/**
 * Generate a scene image using the V4 pipeline:
 * Multi-LoRA scene generation → Easel face swap.
 *
 * Flow:
 * 1. Determine SFW/NSFW mode
 * 2. Fetch approved face URLs + gender for each character
 * 3. Run multi-LoRA scene generation (Flux Dev + uncensored LoRA for NSFW)
 * 4. Run face swap with character face portraits
 * 5. Return final image buffer + metadata
 */
export async function generateSceneImageV4(
  params: V4GenerateSceneParams,
): Promise<V4SceneResult> {
  const { imgPrompt, seriesId, seed } = params;
  const promptId = imgPrompt.id;

  // ── Mode ──
  const isNsfw = imgPrompt.image_type === "website_nsfw_paired";
  const mode: "sfw" | "nsfw" = isNsfw ? "nsfw" : "sfw";

  // ── Character faces + gender ──
  let primaryFaceUrl: string | null = null;
  let primaryGender: "male" | "female" = "female";
  let secondaryFaceUrl: string | null = null;
  let secondaryGender: "male" | "female" = "male";

  if (imgPrompt.character_id) {
    const charName = imgPrompt.character_name || "Unknown";
    [primaryFaceUrl, primaryGender] = await Promise.all([
      fetchApprovedFaceUrl(seriesId, imgPrompt.character_id, charName),
      getCharacterGender(imgPrompt.character_id),
    ]);
    console.log(`[V4][${promptId}] Primary "${charName}": face=${primaryFaceUrl ? 'yes' : 'NO'}, gender=${primaryGender}`);
  }

  if (imgPrompt.secondary_character_id) {
    const secondaryName = imgPrompt.secondary_character_name || "Unknown";
    [secondaryFaceUrl, secondaryGender] = await Promise.all([
      fetchApprovedFaceUrl(seriesId, imgPrompt.secondary_character_id, secondaryName),
      getCharacterGender(imgPrompt.secondary_character_id),
    ]);
    console.log(`[V4][${promptId}] Secondary "${secondaryName}": face=${secondaryFaceUrl ? 'yes' : 'NO'}, gender=${secondaryGender}`);
  }

  const isDualCharacter = !!imgPrompt.secondary_character_id;
  const aspectRatio = isDualCharacter ? "3:2" : "2:3";
  const hasFaceSwap = !!primaryFaceUrl;

  // ── Generate ──
  console.log(
    `[V4][${promptId}] === GENERATION SUMMARY ===\n` +
    JSON.stringify({
      pipeline: "V4 (multi-lora + face-swap)",
      promptId,
      primaryCharacter: imgPrompt.character_id
        ? { id: imgPrompt.character_id, name: imgPrompt.character_name, gender: primaryGender, hasFace: !!primaryFaceUrl }
        : null,
      secondaryCharacter: imgPrompt.secondary_character_id
        ? { id: imgPrompt.secondary_character_id, name: imgPrompt.secondary_character_name, gender: secondaryGender, hasFace: !!secondaryFaceUrl }
        : null,
      aspectRatio,
      mode,
      seed,
      hasFaceSwap,
      promptLength: imgPrompt.prompt.length,
    }, null, 2),
  );

  const result: V4PipelineResult = await runV4Pipeline({
    prompt: imgPrompt.prompt,
    primaryFaceUrl: primaryFaceUrl || "",
    primaryGender,
    secondaryFaceUrl: secondaryFaceUrl || undefined,
    secondaryGender,
    isNsfw,
    aspectRatio,
    seed,
  });

  return {
    imageBuffer: result.finalImageBuffer,
    imageBase64: result.finalImageBase64,
    assembledPrompt: imgPrompt.prompt,
    mode,
    seed: result.seed,
    engine: "flux2_pro",
    hasFaceSwap,
    sceneImageBase64: result.sceneImageBase64,
  };
}
